# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88019eacafac4903b317255698ed5a68445fa34e07455526b2aec5aca991837adf373c754fd853560e5da57ee3c9bd6dcb39aeb6d22cbc6e5230fa4dd3aa37ee

test:
  secret_key_base: 95e115826c6e2da565234545269dc9ab944a2f4ade25f572f9c8ec8e3a40f8a57afdb861bcc172cc50bb07ae0f51a47c0cd2d365e53c1db1064e4b80158916c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
